"""add_opencv_columns

Revision ID: 0227b3e959d3
Revises: 5ef426dbcd9b
Create Date: 2025-02-11 07:48:31.746400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0227b3e959d3'
down_revision: Union[str, None] = '5ef426dbcd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 