"""add_opencv_analysis_columns

Revision ID: 5ef426dbcd9b
Revises: e906fe59f3b7
Create Date: 2025-02-11 07:35:29.919616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef426dbcd9b'
down_revision: Union[str, None] = 'e906fe59f3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('faces_detected', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('dominant_colors', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('average_color', sa.String(), nullable=True))
    op.add_column('media_assets', sa.Column('is_blurry', sa.Boolean(), nullable=True))
    op.add_column('media_assets', sa.Column('brightness_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'brightness_score')
    op.drop_column('media_assets', 'is_blurry')
    op.drop_column('media_assets', 'average_color')
    op.drop_column('media_assets', 'dominant_colors')
    op.drop_column('media_assets', 'faces_detected')
    # ### end Alembic commands ### 