"""add_file_dates

Revision ID: 9ab8ff84a114
Revises: b4490ef02a48
Create Date: 2025-02-11 02:52:13.940891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab8ff84a114'
down_revision: Union[str, None] = 'b4490ef02a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('file_created_date', sa.DateTime(), nullable=True))
    op.add_column('media_assets', sa.Column('file_modified_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'file_modified_date')
    op.drop_column('media_assets', 'file_created_date')
    # ### end Alembic commands ### 