"""add_metadata_columns

Revision ID: b4490ef02a48
Revises: 1b28939bc986
Create Date: 2025-02-11 02:25:29.835380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4490ef02a48'
down_revision: Union[str, None] = '1b28939bc986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('original_creation_date', sa.DateTime(), nullable=True))
    op.add_column('media_assets', sa.Column('upload_date', sa.DateTime(), nullable=True))
    op.add_column('media_assets', sa.Column('title', sa.String(), nullable=True))
    op.add_column('media_assets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('media_assets', sa.Column('bitrate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'bitrate')
    op.drop_column('media_assets', 'duration')
    op.drop_column('media_assets', 'height')
    op.drop_column('media_assets', 'width')
    op.drop_column('media_assets', 'description')
    op.drop_column('media_assets', 'title')
    op.drop_column('media_assets', 'upload_date')
    op.drop_column('media_assets', 'original_creation_date')
    op.drop_column('media_assets', 'file_size')
    # ### end Alembic commands ### 