"""Initial migration

Revision ID: c7887343a104
Revises: 
Create Date: 2025-02-11 19:51:31.389061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7887343a104'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('fps', sa.Float(), nullable=True))
    op.add_column('media_assets', sa.Column('total_frames', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('scene_changes', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('shot_types', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('camera_motion', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('motion_score', sa.Float(), nullable=True))
    op.add_column('media_assets', sa.Column('is_stable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'is_stable')
    op.drop_column('media_assets', 'motion_score')
    op.drop_column('media_assets', 'camera_motion')
    op.drop_column('media_assets', 'shot_types')
    op.drop_column('media_assets', 'scene_changes')
    op.drop_column('media_assets', 'total_frames')
    op.drop_column('media_assets', 'fps')
    # ### end Alembic commands ###
