"""add_search_related_columns

Revision ID: e906fe59f3b7
Revises: 9ab8ff84a114
Create Date: 2025-02-11 04:07:41.848203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e906fe59f3b7'
down_revision: Union[str, None] = '9ab8ff84a114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 